using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FUI.SourceGenerator
{
    /// <summary>
    /// 代码生成工具类
    /// </summary>
    public static class Utility
    {
        /// <summary>
        /// 绑定上下文默认命名空间
        /// </summary>
        public const string BindingContextDefaultNamespace = "FUI.Generated.DataBinding";

        /// <summary>
        /// 文件头
        /// </summary>
        public const string FileHeader = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FUI.SourceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

";

        /// <summary>
        /// 将字符串转换为合法的C#标识符
        /// </summary>
        public static string ToCSharpIdentifier(this string str)
        {
            if (string.IsNullOrEmpty(str))
                return str;

            return str.Replace("<", "_")
                .Replace(">", "_")
                .Replace(".", "_")
                .Replace("/", "_")
                .Replace("\\", "_")
                .Replace(":", "_")
                .Replace(";", "_")
                .Replace(" ", "")
                .Replace("'", "_")
                .Replace("@", "")
                .Replace("&", "")
                .Replace("(", "")
                .Replace(")", "")
                .Replace(",", "_")
                .Replace("[", "_")
                .Replace("]", "_");
        }

        /// <summary>
        /// 获取一个类型的名称（不含命名空间）
        /// </summary>
        /// <param name="typeFullName">类型名全称</param>
        /// <param name="namespace">命名空间</param>
        /// <returns></returns>
        public static string GetTypeName(this string typeFullName, string @namespace)
        {
            return typeFullName.Replace(@namespace + ".", "");
        }

        /// <summary>
        /// 格式化代码
        /// </summary>
        public static string FormatCode(string code)
        {
            try
            {
                var tree = CSharpSyntaxTree.ParseText(code);
                var root = tree.GetRoot();
                return root.NormalizeWhitespace().ToFullString();
            }
            catch
            {
                // 格式化失败时返回原始代码
                return code;
            }
        }

        /// <summary>
        /// 获取属性变更委托名称
        /// </summary>
        public static string GetPropertyChangedDelegateName(string propertyName)
        {
            return $"_{propertyName}_Changed";
        }

        /// <summary>
        /// 获取属性backing field名称
        /// </summary>
        public static string GetPropertyBackingFieldName(string propertyName)
        {
            return $"_{propertyName}__BackingField";
        }

        /// <summary>
        /// 生成带头部信息的代码
        /// </summary>
        public static string GenerateCodeWithHeader(string content)
        {
            var header = string.Format(FileHeader, 
                "1.0.0", 
                "<Generated Time>");
            
            return header + content;
        }

        public static bool IsObservableObject(this ClassDeclarationSyntax classDeclaration)
        {
            // 检查类本身是否有Binding特性
            if (Utility.TryGetViewBindingAttribute(classDeclaration.AttributeLists, out _))
            {
                return true;
            }

            // 检查属性是否有Binding特性
            foreach (var member in classDeclaration.Members.OfType<PropertyDeclarationSyntax>())
            {
                if (Utility.TryGetPropertyBindingAttributes(member.AttributeLists, out _))
                {
                    return true;
                }
            }

            // 检查方法是否有Command特性
            foreach (var member in classDeclaration.Members.OfType<MethodDeclarationSyntax>())
            {
                if (Utility.TryGetCommandAttributes(member.AttributeLists, out _))
                {
                    return true;
                }
            }

            // 检查事件是否有Command特性
            foreach (var member in classDeclaration.Members.OfType<EventDeclarationSyntax>())
            {
                if (Utility.TryGetCommandAttributes(member.AttributeLists, out _))
                {
                    return true;
                }
            }

            // 检查事件字段是否有Command特性
            foreach (var member in classDeclaration.Members.OfType<EventFieldDeclarationSyntax>())
            {
                if (Utility.TryGetCommandAttributes(member.AttributeLists, out _))
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// 获取视图绑定特性参数
        /// </summary>
        public static bool TryGetViewBindingAttribute(SyntaxList<AttributeListSyntax> attributeLists, out AttributeSyntax viewBindingAttribute)
        {
            viewBindingAttribute = null;
            var viewBindingAttributeNames = new[] { "ViewBinding", "ViewBindingAttribute", "FUI.ViewBinding", "FUI.ViewBindingAttribute" };
            
            foreach (var attributeList in attributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    var name = attribute.Name.ToString();
                    if (viewBindingAttributeNames.Contains(name))
                    {
                        viewBindingAttribute = attribute;
                        return true;
                    }
                }
            }
            
            return false;
        }

        /// <summary>
        /// 获取属性绑定特性参数
        /// </summary>
        public static bool TryGetPropertyBindingAttributes(SyntaxList<AttributeListSyntax> attributeLists, out List<AttributeSyntax> attributes)
        {
            attributes = new List<AttributeSyntax>();
            
            var bindingAttributeNames = new[] { "Binding", "BindingAttribute", "FUI.Binding", "FUI.BindingAttribute" };
            
            foreach (var attributeList in attributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    var name = attribute.Name.ToString();
                    if (bindingAttributeNames.Contains(name))
                    {
                        attributes.Add(attribute);
                    }
                }
            }
            
            return attributes.Count > 0;
        }

        /// <summary>
        /// 获取命令特性参数
        /// </summary>
        public static bool TryGetCommandAttributes(SyntaxList<AttributeListSyntax> attributeLists, out List<AttributeSyntax> attributes)
        {
            attributes = new List<AttributeSyntax>();
            
            var commandAttributeNames = new[] { "Command", "CommandAttribute", "FUI.Command", "FUI.CommandAttribute" };
            
            foreach (var attributeList in attributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    var name = attribute.Name.ToString();
                    if (commandAttributeNames.Contains(name))
                    {
                        attributes.Add(attribute);
                    }
                }
            }
            
            return attributes.Count > 0;
        }

        /// <summary>
        /// 获取事件方法名称
        /// </summary>
        public static string GetEventMethodName(string eventName)
        {
            return $"__EventMethod_{eventName}";
        }

        /// <summary>
        /// 转换Location为LocationInfo
        /// </summary>
        public static LocationInfo ToLocationInfo(this Location location)
        {
            var lineSpan = location.GetLineSpan();
            return new LocationInfo
            {
                path = location.SourceTree?.FilePath ?? string.Empty,
                line = lineSpan.StartLinePosition.Line + 1, // 转换为1基索引
                column = lineSpan.StartLinePosition.Character + 1
            };
        }

        /// <summary>
        /// 获取绑定上下文类型名
        /// </summary>
        /// <param name="contextInfo">上下文信息</param>
        /// <returns></returns>
        public static string GetBindingContextTypeName(ContextBindingInfo contextInfo)
        {
            return $"{contextInfo.viewModelType.ToCSharpIdentifier()}_{contextInfo.viewName}_Binding_Generated";
        }

        /// <summary>
        /// 获取绑定上下文类型全称
        /// </summary>
        /// <param name="contextInfo">上下文信息</param>
        /// <returns></returns>
        public static string GetBindingContextTypeFullName(ContextBindingInfo contextInfo)
        {
            return $"{BindingContextDefaultNamespace}.{GetBindingContextTypeName(contextInfo)}";
        }

        /// <summary>
        /// 获取绑定上下文基类类型名
        /// </summary>
        /// <param name="contextInfo"></param>
        /// <returns></returns>
        public static string GetBindingContextBaseTypeName(ContextBindingInfo contextInfo)
        {
            if(contextInfo.baseViewModelType == null)
            {
                return $"FUI.BindingContext<{contextInfo.viewModelType}>";
            }

            var baseViewModelTypeName = contextInfo.baseViewModelType.GetTypeName(contextInfo.baseViewModelNamespace);
            return $"{contextInfo.baseViewModelNamespace}.{baseViewModelTypeName}.{baseViewModelTypeName}_{contextInfo.baseViewName}_BindingContext";
        }

        /// <summary>
        /// 判断某个类型是否需要生成绑定上下文
        /// </summary>
        public static bool NeedGenerateBindingContext(this ITypeSymbol type)
        {
            if (type == null)
            {
                return false;
            }

            // 排除框架内基类自身
            var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", string.Empty);
            if (fullName == "FUI.ViewModel" ||
                fullName == "FUI.Bindable.ObservableObject")
            {
                return false;
            }

            // 仅处理源码内声明的类型
            if (type.DeclaringSyntaxReferences.Length == 0)
            {
                return false;
            }

            // 检查源语法：必须真正含有绑定相关特性/命令/事件
            foreach (var syntaxRef in type.DeclaringSyntaxReferences)
            {
                if (syntaxRef.GetSyntax() is ClassDeclarationSyntax cls)
                {
                    // 复用语法级判断（有任一绑定/命令/视图特性才为 true）
                    if (cls.IsObservableObject())
                    {
                        return true;
                    }
                }
            }

            return false;
        }
    }
}