using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace FUI.SourceGenerator.Generators
{
    /// <summary>
    /// 绑定上下文信息生成器
    /// </summary>
    [Generator]
    public partial class BindingContextInfoGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// 初始化增量生成器
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 语法筛选：类声明
            var classProvider = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => TransformToBindingInfos(ctx, ct))
                .Where(static x => x != null);

            // 展开列表并输出源码
            var flattened = classProvider.SelectMany(static (list, _) => list);

            context.RegisterSourceOutput(flattened, static (spc, bindingInfo) =>
            {
                if (bindingInfo == null)
                {
                    return;
                }

                var code = BuildContextInfoCode(bindingInfo);
                code = Utility.FormatCode(code);
                var viewNameFormat = string.IsNullOrEmpty(bindingInfo.viewName) ? "Empty" : bindingInfo.viewName;
                var fileName = $"{bindingInfo.viewModelType}.{viewNameFormat}.BindingInfo.g";
                spc.AddSource(fileName, code);
            });
        }

        /// <summary>
        /// 将类语法节点转换为绑定信息集合
        /// </summary>
        static List<ContextBindingInfo> TransformToBindingInfos(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            var classDeclaration = ctx.Node as ClassDeclarationSyntax;
            if (classDeclaration == null)
            {
                return null;
            }

            // 跳过已生成文件
            var filePath = classDeclaration.SyntaxTree?.FilePath ?? string.Empty;
            if (IsGeneratedFile(filePath, classDeclaration.SyntaxTree))
            {
                return null;
            }

            var typeSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            if (typeSymbol == null)
            {
                return null;
            }

            // 仅处理可观察对象
            if (!typeSymbol.IsObservableObject())
            {
                return null;
            }

            // 仅在类型的首个声明处生成，避免 partial 多次生成
            var declaringRefs = typeSymbol.DeclaringSyntaxReferences;
            if (declaringRefs != null && declaringRefs.Length > 0)
            {
                var primary = declaringRefs[0];
                if (!(primary.SyntaxTree == classDeclaration.SyntaxTree && primary.Span.Start == classDeclaration.SpanStart))
                {
                    return null;
                }
            }

            var compilation = ctx.SemanticModel.Compilation;
            var generator = new ContextInfoByAttributeGenerator();
            // 在增量生成中不需要真正的 GeneratorExecutionContext，传递 default 即可
            var infos = generator.Generate(default, compilation, classDeclaration);
            return infos != null && infos.Count > 0 ? infos : null;
        }

        /// <summary>
        /// 判断是否为已生成文件
        /// </summary>
        static bool IsGeneratedFile(string filePath, SyntaxTree tree)
        {
            if (string.IsNullOrEmpty(filePath))
            {
                return false;
            }

            // 常见生成文件后缀
            if (filePath.EndsWith(".g.cs") || filePath.EndsWith(".generated.cs"))
            {
                return true;
            }

            // 尝试检测文件头的 auto-generated 标识
            var text = tree.GetText();
            var span = text.Lines.Count > 0 ? text.Lines[0].Span : default;
            var firstLine = span.Length > 0 ? text.ToString(span) : string.Empty;
            if (!string.IsNullOrEmpty(firstLine) && firstLine.IndexOf("<auto-generated>") >= 0)
            {
                return true;
            }

            return false;
        }
    }
}
